
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


def fun():
    print("correct")

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Github\ISL MEDIAPIPE\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("837x595")
window.configure(bg = "#006FD5")


canvas = Canvas(
    window,
    bg = "#006FD5",
    height = 595,
    width = 837,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    409.0,
    0.0,
    837.0,
    595.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    627.0,
    219.0,
    image=image_image_1
)

canvas.create_text(
    447.0,
    28.0,
    anchor="nw",
    text="Your Video",
    fill="#006FD5",
    font=("RobotoRoman Medium", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    768.0,
    37.6669921875,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: fun(),
    relief="flat"
)
button_1.place(
    x=447.0,
    y=388.0,
    width=161.248046875,
    height=26.189453125
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=645.8583984375,
    y=388.0,
    width=161.2783203125,
    height=26.189453125
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    627.0,
    490.0,
    image=image_image_3
)

canvas.create_text(
    466.0,
    436.0,
    anchor="nw",
    text="Translation",
    fill="#006FD5",
    font=("RobotoRoman Medium", 15 * -1)
)

canvas.create_text(
    26.0,
    179.0,
    anchor="nw",
    text="Welcome To Sign Language Detector",
    fill="#FFFFFF",
    font=("RobotoRoman Bold", 20 * -1)
)

canvas.create_text(
    26.0,
    242.0,
    anchor="nw",
    text="Sign language detector is a project built by students of",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    26.0,
    274.0,
    anchor="nw",
    text="Siddaganga Institute of Technology, Under the guidance of",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    26.0,
    306.0,
    anchor="nw",
    text="Dr Nagaratna B. Chittaragi",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    26.0,
    356.0,
    anchor="nw",
    text="By using power of MediaPipe,  this tool converts the",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    26.0,
    388.0,
    anchor="nw",
    text="Indian Sign Language visual input into textual output",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_text(
    26.0,
    420.0,
    anchor="nw",
    text="by converting the sign inputs.",
    fill="#FFFFFF",
    font=("Roboto", 15 * -1)
)

canvas.create_rectangle(
    26.0,
    220.0,
    82.0,
    224.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    60.0,
    27.0,
    anchor="nw",
    text="Sign Language Detection",
    fill="#C3E9FF",
    font=("RobotoRoman Medium", 20 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    37.0,
    38.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
